export type InsiderTracker = {
  id: string;
  name: string;
  type: "youtube" | "twitter";
  channelId?: string;
  handle?: string;
  avatar: string;
  color: string;
  category: string;
};

export const INSIDER_TRACKERS: InsiderTracker[] = [
  {
    id: "whyfiles",
    name: "The Why Files",
    type: "youtube",
    channelId: "UCIFk2uvCNcEmZ77g0ESKLcQ",
    avatar: "🔍",
    color: "#00ff88",
    category: "uap",
  },
  {
    id: "coulthart",
    name: "Ross Coulthart",
    type: "youtube",
    channelId: "UCW-NJDzqcE7eC5lZu3xL7hA",
    avatar: "📡",
    color: "#00bb66",
    category: "uap",
  },
  {
    id: "secureteam",
    name: "SecureTeam10",
    type: "youtube",
    channelId: "UC4F3j3ed_To-M3H2YLLD5vw",
    avatar: "🛸",
    color: "#8aa6ff",
    category: "uap",
  },
  {
    id: "grusch_tw",
    name: "David Grusch",
    type: "twitter",
    handle: "DavidCharlesGrusch",
    avatar: "🎖️",
    color: "#00ff88",
    category: "uap",
  },
  {
    id: "graves_tw",
    name: "Ryan Graves",
    type: "twitter",
    handle: "uncertainvector",
    avatar: "✈️",
    color: "#00bb66",
    category: "uap",
  },
  {
    id: "mellon_tw",
    name: "Chris Mellon",
    type: "twitter",
    handle: "ChristopherMellon",
    avatar: "🏛️",
    color: "#8aa6ff",
    category: "uap",
  },
  {
    id: "coulthart_tw",
    name: "Ross Coulthart",
    type: "twitter",
    handle: "rosscoulthart",
    avatar: "📡",
    color: "#00bb66",
    category: "uap",
  },
  {
    id: "burchett_tw",
    name: "Rep. Tim Burchett",
    type: "twitter",
    handle: "timburchett",
    avatar: "🏛️",
    color: "#c94dff",
    category: "uap",
  },
  {
    id: "carlson_tw",
    name: "Tucker Carlson",
    type: "twitter",
    handle: "TuckerCarlson",
    avatar: "📺",
    color: "#ff6600",
    category: "media",
  },
  {
    id: "bilzerian_tw",
    name: "Dan Bilzerian",
    type: "twitter",
    handle: "DanBilzerian",
    avatar: "🎲",
    color: "#ffaa00",
    category: "media",
  },
  {
    id: "carroll_tw",
    name: "Ian Carroll",
    type: "twitter",
    handle: "IanCarrollShow",
    avatar: "🔎",
    color: "#00bb66",
    category: "media",
  },
  {
    id: "loupis_tw",
    name: "Anastasia Maria Loupis",
    type: "twitter",
    handle: "AnastasiaMLoupis",
    avatar: "⚕️",
    color: "#8aa6ff",
    category: "media",
  },
  {
    id: "owens_tw",
    name: "Candace Owens",
    type: "twitter",
    handle: "RealCandaceO",
    avatar: "🎙️",
    color: "#c94dff",
    category: "commentary",
  },
  {
    id: "fuentes_tw",
    name: "Nick Fuentes",
    type: "twitter",
    handle: "NickJFuentes",
    avatar: "📢",
    color: "#ff3333",
    category: "commentary",
  },
  {
    id: "thunberg_tw",
    name: "Greta Thunberg",
    type: "twitter",
    handle: "GretaThunberg",
    avatar: "🌍",
    color: "#00ff88",
    category: "geopolitics",
  },
  {
    id: "youssef_tw",
    name: "Bassem Youssef",
    type: "twitter",
    handle: "Byoussef",
    avatar: "🎭",
    color: "#ffaa00",
    category: "geopolitics",
  },
  {
    id: "atwan_tw",
    name: "Abdel Bari Atwan",
    type: "twitter",
    handle: "bbatwan",
    avatar: "📰",
    color: "#8aa6ff",
    category: "geopolitics",
  },
  {
    id: "suleiman_tw",
    name: "Omar Suleiman",
    type: "twitter",
    handle: "omarsuleiman504",
    avatar: "☪️",
    color: "#00bb66",
    category: "geopolitics",
  },
];
