export type ToolkitItem = {
  name: string;
  url: string;
  /** One line — why an investigator or builder cares. */
  blurb: string;
};

export type ToolkitCategory = {
  id: string;
  title: string;
  subtitle: string;
  accent: string;
  /** Shown above category when set (legal / ethics note). */
  disclaimer?: string;
  items: ToolkitItem[];
};

export const TOOLKIT_CATEGORIES: ToolkitCategory[] = [
  {
    id: "scrape",
    title: "Scrape & ingest",
    subtitle: "Turn the open web into LLM-ready text — powers our feed scraper and Oracle research.",
    accent: "#00ff88",
    items: [
      { name: "Firecrawl", url: "https://www.firecrawl.dev/", blurb: "Site → clean markdown/JSON; pairs well with Brave search for article research." },
      { name: "firecrawl (GitHub)", url: "https://github.com/firecrawl/firecrawl", blurb: "Open-source core; self-host or inspect the scrape pipeline." },
      { name: "Crawl4AI", url: "https://github.com/unclecode/crawl4ai", blurb: "Async crawl tuned for RAG — fast article body extraction." },
      { name: "browser-use", url: "https://github.com/browser-use/browser-use", blurb: "LLM-driven browser agent for flows plain HTTP cannot reach." },
      { name: "video-use", url: "https://github.com/browser-use/video-use", blurb: "Browser agent variant aimed at video-heavy pages." },
      { name: "Crawlee", url: "https://github.com/apify/crawlee", blurb: "Production scraper framework (Playwright/Puppeteer) with queues and retries." },
      { name: "Scrapy", url: "https://github.com/scrapy/scrapy", blurb: "Classic Python spider framework — still unbeatable for large crawls." },
      { name: "MarkItDown", url: "https://github.com/microsoft/markitdown", blurb: "Microsoft utility: PDF, Office, HTML → markdown for LLM ingestion." },
      { name: "Scrapling", url: "https://github.com/D4Vinci/Scrapling", blurb: "Adaptive scraping — handles DOM changes better than brittle selectors." },
      { name: "AutoScraper", url: "https://github.com/alirezamika/autoscraper", blurb: "Learns patterns from examples; good for repetitive news layouts." },
      { name: "curl-impersonate", url: "https://github.com/lwthiker/curl-impersonate", blurb: "TLS/browser fingerprint mimicry when sites block datacenter IPs." },
      { name: "open-lovable", url: "https://github.com/firecrawl/open-lovable", blurb: "Firecrawl + app builder experiment — scrape-to-UI prototyping." },
    ],
  },
  {
    id: "osint",
    title: "OSINT & investigation",
    subtitle: "Username pivots, breach data, maps, and document trails — Oracle board fuel.",
    accent: "#ffaa00",
    items: [
      { name: "Sherlock", url: "https://github.com/sherlock-project/sherlock", blurb: "Hunt a username across 400+ sites — first stop for identity pivots." },
      { name: "SomaliScan — Epstein Index", url: "https://www.somaliscan.com/investigation/epstein-index", blurb: "Structured investigation index — reference for deep-dive articles." },
      { name: "theHarvester", url: "https://github.com/laramies/theHarvester", blurb: "Emails, subdomains, and hosts from public sources." },
      { name: "SpiderFoot", url: "https://github.com/smicallef/spiderfoot", blurb: "Automated OSINT correlation engine with 200+ modules." },
      { name: "Shodan", url: "https://www.shodan.io/", blurb: "Internet-wide device/service search — exposed cameras, ICS, misconfigs." },
      { name: "Have I Been Pwned", url: "https://haveibeenpwned.com/", blurb: "Breach lookup for emails and passwords." },
      { name: "DeHashed", url: "https://dehashed.com/", blurb: "Paid breach/credential search with rich filters." },
      { name: "LeakCheck", url: "https://leakcheck.io/", blurb: "Another breach index — cross-check findings." },
      { name: "FaceCheck.ID", url: "https://facecheck.id/", blurb: "Reverse face search across the public web." },
      { name: "PimEyes", url: "https://pimeyes.com/en", blurb: "Face search engine — use responsibly and verify legally." },
      { name: "ExifTool", url: "https://exiftool.org/", blurb: "Extract GPS, camera, and edit history from images and PDFs." },
      { name: "Jimpl EXIF viewer", url: "https://jimpl.com/", blurb: "Browser-side EXIF strip/view — quick photo metadata checks." },
      { name: "WiGLE", url: "https://wigle.net/", blurb: "Wireless network geolocation — map SSIDs and MAC addresses." },
      { name: "Google Hacking Database", url: "https://www.exploit-db.com/google-hacking-database", blurb: "Classic Google dork patterns for exposed files and panels." },
      { name: "deviceinfo.me", url: "https://www.deviceinfo.me/", blurb: "What your browser leaks (IP, UA, WebRTC) — tradecraft baseline." },
      { name: "IntelTechniques Tools", url: "https://inteltechniques.com/tools/index.html", blurb: "Mike Bazzell's curated OSINT tool menu — industry standard reference." },
      { name: "Ultimate OSINT Collection", url: "https://start.me/p/DPYPMz/the-ultimate-osint-collection", blurb: "Start.me dashboard — hundreds of OSINT bookmarks in one place." },
      { name: "OSINT on Chain", url: "https://osint.intelligenceonchain.com/", blurb: "Blockchain-adjacent OSINT resources." },
      { name: "PentestList", url: "https://pentestlist.com/", blurb: "Searchable pentest/OSINT tool directory." },
      { name: "UseOdin", url: "https://www.useodin.net/", blurb: "OSINT platform for analysts." },
      { name: "Osiris AI Live Map", url: "https://www.osirisai.live/", blurb: "Global incidents, CCTV, earthquakes, live news — situational awareness layer." },
      { name: "ExtractFace", url: "https://github.com/mrpnkt/ExtractFace", blurb: "Facebook photo/face extraction helpers for authorized research." },
      { name: "fb-sleep-stats", url: "https://github.com/sorenlouv/fb-sleep-stats", blurb: "Activity-pattern analysis from public Facebook signals." },
      { name: "st3gg", url: "https://github.com/elder-plinius/st3gg", blurb: "OSINT / threat-hunting utilities collection." },
      { name: "PentAGI", url: "https://github.com/vxcontrol/pentagi", blurb: "Autonomous pentest agent — research only on systems you own." },
      { name: "The art of pivoting", url: "https://hatless1der.com/advanced-osint-the-art-of-pivoting/", blurb: "Essay on OSINT pivot methodology." },
      { name: "GPX Editor map", url: "https://www.gpxeditor.co.uk/map", blurb: "Verify geolocation claims against GPX/track data." },
    ],
  },
  {
    id: "agents",
    title: "AI agents & orchestration",
    subtitle: "Multi-step research, coding agents, and workflow runners.",
    accent: "#c94dff",
    items: [
      { name: "agency-agents", url: "https://github.com/msitarzewski/agency-agents", blurb: "Multi-agent agency pattern — specialist roles in one pipeline." },
      { name: "DeerFlow", url: "https://github.com/bytedance/deer-flow", blurb: "ByteDance deep-research agent framework." },
      { name: "Hermes Agent", url: "https://hermes-agent.org/", blurb: "Long-horizon agent runtime." },
      { name: "Codex Orchestration", url: "https://github.com/Cjbuilds/Codex-Orchestration", blurb: "Orchestrate Codex/CLI agents across tasks." },
      { name: "oh-my-claudecode", url: "https://github.com/Yeachan-Heo/oh-my-claudecode", blurb: "Claude Code power-user tooling and workflows." },
      { name: "everything-claude-code", url: "https://github.com/affaan-m/everything-claude-code", blurb: "Curated Claude Code configs, hooks, and patterns." },
      { name: "GitHub spec-kit", url: "https://github.com/github/spec-kit", blurb: "Spec-driven development — plan before you ship." },
      { name: "Dify", url: "https://github.com/langgenius/dify", blurb: "Visual LLM app builder — prototype Oracle-style flows without code." },
      { name: "MiroFish", url: "https://github.com/666ghj/MiroFish", blurb: "Multi-agent simulation / swarm experiments." },
      { name: "PLFM RADAR", url: "https://github.com/NawfalMotii79/PLFM_RADAR", blurb: "Radar-style monitoring agent project." },
      { name: "Cursor Automations", url: "https://cursor.com/docs/cloud-agent/automations", blurb: "Scheduled cloud agents — cron backup for scrapers and briefings." },
      { name: "DeepTutor", url: "https://github.com/HKUDS/DeepTutor", blurb: "AI tutoring / research agent from HKUDS." },
      { name: "mempalace", url: "https://github.com/milla-jovovich/mempalace", blurb: "Agent memory layer experiments." },
      { name: "RuView", url: "https://github.com/ruvnet/RuView", blurb: "Agent/view tooling for Ruvnet stack." },
      { name: "meta-llm-charter", url: "https://github.com/entropyvortex/meta-llm-charter", blurb: "Governance patterns for multi-model agent systems." },
      { name: "Odysseus", url: "https://pewdiepie-archdaemon.github.io/odysseus/", blurb: "Local-first agent runtime concept." },
      { name: "TaxHacker", url: "https://github.com/vas3k/TaxHacker", blurb: "Document → structured data agent (receipts, forms)." },
      { name: "block/buzz", url: "https://github.com/block/buzz", blurb: "Block's agent experimentation repo." },
    ],
  },
  {
    id: "media",
    title: "Media, launch & video",
    subtitle: "Short-form video, launch reels, and audio — complements Brag Studio.",
    accent: "#ff6666",
    items: [
      { name: "/brag", url: "https://github.com/latent-spaces/brag", blurb: "Hyperframes launch videos — integrated in our admin Brag Studio." },
      { name: "OpenMontage", url: "https://github.com/calesthio/OpenMontage", blurb: "Open video montage tooling." },
      { name: "MoneyPrinterTurbo", url: "https://github.com/harry0703/MoneyPrinterTurbo", blurb: "Automated short video from script — TikTok/Reels pipeline." },
      { name: "Lightreel", url: "https://lightreel.ai/landing", blurb: "AI video reel generation." },
      { name: "Supertonic (TTS)", url: "https://github.com/supertone-inc/supertonic", blurb: "Expressive TTS for video voiceovers." },
      { name: "voicebox", url: "https://github.com/jamiepine/voicebox", blurb: "Local voice cloning / TTS workstation." },
      { name: "LongCat Video", url: "https://github.com/meituan-longcat/LongCat-Video", blurb: "Meituan long-form video generation research." },
      { name: "LongCat Avatar 1.5", url: "https://huggingface.co/meituan-longcat/LongCat-Video-Avatar-1.5", blurb: "Talking-head avatar model weights." },
      { name: "OpenGame", url: "https://github.com/leigest519/OpenGame", blurb: "Game/video interactive generation experiments." },
      { name: "SongGeneration Studio", url: "https://github.com/BazedFrog/SongGeneration-Studio", blurb: "AI music generation UI." },
      { name: "img2threejs", url: "https://github.com/hoainho/img2threejs", blurb: "Image → 3D scene for visual explainers." },
      { name: "Three.js Object Sculptor", url: "https://github.com/vinhhien112/Three.js-Object-Sculptor-Codex-Plugin", blurb: "Codex plugin for 3D object authoring." },
      { name: "animate-ui", url: "https://github.com/imskyleen/animate-ui", blurb: "Animated UI components for launch pages." },
      { name: "Higgsfield Supercomputer", url: "https://higgsfield.ai/supercomputer", blurb: "High-end generative video platform." },
    ],
  },
  {
    id: "models",
    title: "Models & inference",
    subtitle: "Weights, OCR, speech, and local runtimes — for self-hosted research stacks.",
    accent: "#00d4ff",
    items: [
      { name: "GLM-OCR", url: "https://github.com/zai-org/GLM-OCR", blurb: "Document OCR model — declassified PDF pipelines." },
      { name: "Open LM GLM-5.2", url: "https://openlm.ai/glm-5.2/", blurb: "GLM model family hub." },
      { name: "Qwen3.6 35B GGUF", url: "https://huggingface.co/unsloth/Qwen3.6-35B-A3B-GGUF", blurb: "Quantized Qwen for local inference." },
      { name: "Qwen distilled reasoning", url: "https://huggingface.co/Jackrong/Qwen3.5-27B-Claude-4.6-Opus-Reasoning-Distilled", blurb: "Distilled reasoning model experiment." },
      { name: "speech-to-speech", url: "https://github.com/huggingface/speech-to-speech", blurb: "HF real-time speech pipeline." },
      { name: "Hungarian GPT-2 news", url: "https://huggingface.co/NYTK/text-generation-news-gpt2-small-hungarian", blurb: "Small Hungarian news LM — niche locale experiments." },
      { name: "Kronos", url: "https://github.com/shiyu-coder/Kronos", blurb: "Time-series / forecasting model tooling." },
      { name: "Wan2GP", url: "https://github.com/deepbeepmeep/Wan2GP", blurb: "GPU-optimized Wan video model runner." },
      { name: "PixelRAG", url: "https://github.com/StarTrail-org/PixelRAG", blurb: "Visual RAG — images in retrieval pipelines." },
      { name: "Open Higgsfield AI", url: "https://github.com/Anil-matcha/Open-Higgsfield-AI", blurb: "Open replication/experiments around Higgsfield." },
      { name: "CorridorKey", url: "https://github.com/nikopueringer/CorridorKey", blurb: "Model routing / key management utility." },
      { name: "picoclaw", url: "https://picoclaw.io/", blurb: "Tiny local agent runtime." },
      { name: "entropic (Qu.ai)", url: "https://entropic.qu.ai/pricing", blurb: "Managed inference pricing — compare against self-host." },
    ],
  },
  {
    id: "dev",
    title: "Dev, deploy & product",
    subtitle: "Ship and run The Theorist-style stacks without enterprise lock-in.",
    accent: "#8aa6ff",
    items: [
      { name: "Coolify", url: "https://github.com/coollabsio/coolify", blurb: "Self-host PaaS on your VPS — escape serverless limits." },
      { name: "Chatwoot", url: "https://github.com/chatwoot/chatwoot", blurb: "Open-source support inbox when user base grows." },
      { name: "Maybe Finance", url: "https://github.com/maybe-finance/maybe", blurb: "Open personal finance — if you monetize later." },
      { name: "AdKit", url: "https://adkit.so/", blurb: "Ad creative generation — growth layer for The Theorist." },
      { name: "Shipper", url: "https://app.shipper.now/", blurb: "Fast product shipping toolkit." },
      { name: "usefastlane.ai", url: "https://www.usefastlane.ai/", blurb: "AI-accelerated product lanes." },
      { name: "indiepa.ge", url: "https://indiepa.ge/", blurb: "Indie maker landing pages." },
      { name: "tiiny.ai", url: "https://tiiny.ai/", blurb: "Micro-SaaS / landing experiments." },
      { name: "ui-ux-pro-max-skill", url: "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill", blurb: "UI/UX skill pack for agent-assisted design." },
      { name: "ai-website-cloner", url: "https://github.com/JCodesMore/ai-website-cloner-template", blurb: "Clone-and-remix site templates with agents." },
      { name: "Skills (MengTo)", url: "https://github.com/MengTo/Skills", blurb: "Design/dev skill definitions for Claude." },
      { name: "Skills (lixiaolin94)", url: "https://github.com/lixiaolin94/skills", blurb: "Additional agent skill library." },
      { name: "Anthropic Skilljar", url: "https://anthropic.skilljar.com/", blurb: "Official Anthropic training courses." },
      { name: "walls.rip mail", url: "https://walls.rip/mail", blurb: "Disposable/alias mail for signup tradecraft." },
    ],
  },
  {
    id: "experiments",
    title: "Experiments & builders",
    subtitle: "Playgrounds worth watching — not all production-ready.",
    accent: "#9ec8ae",
    items: [
      { name: "HY-3D", url: "https://hy-3d.com/", blurb: "3D generation playground." },
      { name: "Emergent", url: "https://app.emergent.sh/home", blurb: "Agent app builder sandbox." },
      { name: "CodinGame", url: "https://www.codingame.com/ide/puzzle/onboarding", blurb: "Algorithm puzzles — keeps scraping/parsing skills sharp." },
      { name: "Rork", url: "https://rork.com/", blurb: "Mobile app AI builder." },
      { name: "oiioii.ai", url: "https://www.oiioii.ai/login", blurb: "Creative AI workspace." },
      { name: "Kimi", url: "https://www.kimi.com/membership/pricing", blurb: "Moonshot long-context chat — compare research quality." },
      { name: "UserRebirth", url: "https://userebirth.com/dashboard", blurb: "Growth/analytics experiment." },
      { name: "lemonade.gg", url: "https://lemonade.gg/", blurb: "Gaming/agent crossover project." },
      { name: "linux-android", url: "https://github.com/mayukh4/linux-android", blurb: "Run Linux on Android — field research device." },
      { name: "scrcpy", url: "https://github.com/Genymobile/scrcpy", blurb: "Mirror and control Android from desktop." },
      { name: "Alice", url: "https://github.com/pmbstyle/Alice", blurb: "Personal AI assistant framework." },
    ],
  },
  {
    id: "training",
    title: "OSINT training & tradecraft",
    subtitle: "Skill-building — geolocation, quizzes, courses, and military open-source reading.",
    accent: "#00bb66",
    items: [
      { name: "GeoGuessr", url: "https://www.geoguessr.com/", blurb: "Train geolocation intuition from street-level imagery." },
      { name: "Quiztime (@quiztime)", url: "https://x.com/quiztime", blurb: "Twitter geolocation challenge series — gold standard training." },
      { name: "Introduction to OSINT", url: "https://www.myosint.training/courses/introduction-to-osint", blurb: "Structured beginner OSINT course." },
      { name: "TCM OSINT Course (Notion)", url: "https://www.notion.so/TCM-OSINT-Course-183a035142118024b3c0ea2827350a19", blurb: "Community OSINT curriculum notes." },
      { name: "SOC.mil IdM publications", url: "https://www.soc.mil/IdM/publications/IdMpubs.html", blurb: "US Army intel doctrine — open PDF library." },
      { name: "OSINT pivoting (YouTube)", url: "https://www.youtube.com/watch?v=nd5W82KN9B8", blurb: "Video walkthrough on pivot techniques." },
      { name: "OSINT phone/email (Reddit)", url: "https://www.reddit.com/r/OSINT/comments/15y4wuh/phone_number_and_email/", blurb: "Community thread on number/email pivots." },
    ],
  },
  {
    id: "hardware",
    title: "Hardware & close access",
    subtitle: "Research tooling — authorized testing only. Laws vary by country.",
    accent: "#ff3333",
    disclaimer:
      "For systems you own or have written permission to test. Unauthorized access is illegal. The Theorist links these for defensive awareness and journalist tradecraft education only.",
    items: [
      { name: "USB Army Knife", url: "https://github.com/i-am-shodan/USBArmyKnife/wiki/Installation", blurb: "Multi-function USB research implant — know what defenders detect." },
      { name: "USB Army Knife (overview)", url: "https://www.mobile-hacker.com/2025/01/24/usb-army-knife-the-ultimate-close-access-penetest-tool/", blurb: "Independent write-up of capabilities and risks." },
      { name: "Pwnagotchi", url: "https://pwnagotchi.ai/", blurb: "WiFi handshake capture pet — passive RF research." },
      { name: "Hak5 USB Rubber Ducky", url: "https://shop.hak5.org/products/usb-rubber-ducky", blurb: "Classic keystroke injection research platform." },
      { name: "Alfa AWUS036AXM", url: "https://alfa-network.eu/wi-fi/wi-fi-adapters/alfa-usb-adapter-awus036axm", blurb: "Monitor-mode WiFi adapter for RF surveys." },
      { name: "LilyGo T-Dongle S3", url: "https://lilygo.cc/products/t-dongle-s3", blurb: "Compact ESP32-S3 USB form factor for custom tools." },
    ],
  },
];

export const TOOLKIT_ITEM_COUNT = TOOLKIT_CATEGORIES.reduce((n, c) => n + c.items.length, 0);
