/** Curated UAP reference data — seeded into DB on first full scrape. */

export const UAP_INCIDENTS = [
  { id:"nimitz", name:"USS Nimitz / Tic-Tac", date:"2004-11-14", location:"San Diego, Pacific Ocean", lat:32.5, lng:-117.5, classification:"DECLASSIFIED", evidenceLevel:"HIGH", description:"F/A-18 pilots from USS Nimitz encountered a 40-foot white object with no wings, rotors, or exhaust. It moved at hypersonic speeds and outmaneuvered advanced fighter jets. The FLIR1 video was declassified by the Pentagon in 2020.", witnesses:["David Fravor","Jim Slaight","Alex Dietrich","Chad Underwood"], documents:["FLIR1 Video","UAP Task Force Report 2021","TTSA Release 2017"], relatedOrgs:["USS Nimitz Strike Group","AATIP","TTSA"], tags:["military","verified","video","pentagon"] },
  { id:"roosevelt", name:"USS Roosevelt / Gimbal & GoFast", date:"2015-01-01", location:"US East Coast, Atlantic", lat:34.0, lng:-74.0, classification:"DECLASSIFIED", evidenceLevel:"HIGH", description:"Multiple encounters by F/A-18 pilots over months. Gimbal video shows rotating object with no visible propulsion. Ryan Graves reported near-daily encounters.", witnesses:["Ryan Graves","Danny Accoin"], documents:["Gimbal Video","GoFast Video","Ryan Graves Congressional Testimony 2023"], relatedOrgs:["USS Theodore Roosevelt CVN-71","AARO","US Navy"], tags:["military","verified","video","pentagon","congress"] },
  { id:"rendlesham", name:"Rendlesham Forest Incident", date:"1980-12-26", location:"Suffolk, United Kingdom", lat:52.09, lng:1.45, classification:"REPORTED", evidenceLevel:"MEDIUM", description:"US Air Force personnel witnessed triangular craft in Rendlesham Forest near RAF Bentwaters. Lt. Col. Charles Halt filed official memo, audio recorded. Radiation levels above normal measured at landing site.", witnesses:["Charles Halt","Jim Penniston","John Burroughs"], documents:["Halt Memorandum 1981","UK MoD Release 2001","Halt Audio Recording"], relatedOrgs:["RAF Bentwaters","USAF 81st TFW","UK Ministry of Defence"], tags:["military","radiation","uk","landing"] },
  { id:"phoenix", name:"Phoenix Lights", date:"1997-03-13", location:"Phoenix, Arizona, USA", lat:33.44, lng:-112.07, classification:"REPORTED", evidenceLevel:"MEDIUM", description:"Thousands of witnesses across Arizona and Nevada reported a massive V-shaped formation of lights. Arizona Governor Fife Symington later admitted he saw something inexplicable.", witnesses:["Fife Symington (Governor)","Frances Barwood (City Councilwoman)"], documents:["NUFORC Reports","Phoenix City Council Records"], relatedOrgs:["Luke Air Force Base","Phoenix Police Department"], tags:["mass-sighting","civilian","governor"] },
  { id:"grusch", name:"David Grusch Whistleblower", date:"2023-07-26", location:"Washington DC, USA", lat:38.89, lng:-77.03, classification:"CONFIRMED", evidenceLevel:"HIGH", description:"Former NRO intelligence officer testified under oath before Congress that the US government possesses non-human craft and biological remains. Granted whistleblower protections.", witnesses:["David Grusch","Ryan Graves","David Fravor"], documents:["Congressional Testimony July 2023","IC Inspector General Complaint","DOPSR Cleared Statements"], relatedOrgs:["NRO","AARO","DIA","Congressional UAP Caucus"], tags:["congress","whistleblower","oath","biological"] },
  { id:"ohare", name:"O'Hare Airport UFO", date:"2006-11-07", location:"Chicago, Illinois, USA", lat:41.97, lng:-87.90, classification:"REPORTED", evidenceLevel:"MEDIUM", description:"Dozen United Airlines employees witnessed metallic disc hovering over Gate C17 at O'Hare. Object shot upward through cloud cover leaving circular hole.", witnesses:["United Airlines Gate Supervisors","Ramp Workers","Pilots"], documents:["FAA FOIA Radio Tapes","Chicago Tribune Investigation 2007","NARCAP Report"], relatedOrgs:["United Airlines","FAA","NARCAP"], tags:["civilian","airport","faa","foia"] },
  { id:"belgian", name:"Belgian UFO Wave", date:"1989-11-29", location:"Belgium, Europe", lat:50.85, lng:4.35, classification:"CONFIRMED", evidenceLevel:"HIGH", description:"Over 13,500 witnesses including police officers reported large triangular craft. Belgian Air Force scrambled F-16s twice. Radar confirmed unknown objects.", witnesses:["Belgian Gendarmerie Officers","Belgian AF Pilots","13,500+ civilians"], documents:["Belgian Air Force Official Report","SOBEPS Investigation Files","NATO Radar Data"], relatedOrgs:["Belgian Air Force","Belgian Government","SOBEPS","NATO"], tags:["military","radar","government","europe"] },
  { id:"roswell", name:"Roswell Incident", date:"1947-07-08", location:"Roswell, New Mexico, USA", lat:33.39, lng:-104.52, classification:"ALLEGED", evidenceLevel:"LOW", description:"Ranch foreman found unusual debris. RAAF initially announced recovery of 'flying disc' before retracting. Major Jesse Marcel photographed debris.", witnesses:["Mac Brazel","Jesse Marcel","Glenn Dennis"], documents:["RAAF Press Release July 8 1947","1994 USAF Report","MJ-12 Documents (disputed)"], relatedOrgs:["Roswell Army Air Field","Project Mogul","CIA"], tags:["historical","military","cover-up","debris"] },
  { id:"aaro2024", name:"AARO UAP Historical Review", date:"2024-03-08", location:"Pentagon, Washington DC", lat:38.87, lng:-77.05, classification:"DECLASSIFIED", evidenceLevel:"HIGH", description:"Pentagon's AARO released Vol.1 of Historical Record Report reviewing 70+ years of UAP programs. Contradicts Grusch testimony but acknowledges numerous unresolved cases.", witnesses:["Sean Kirkpatrick (AARO Director)"], documents:["AARO Historical Record Report Vol.1 2024","DoD Press Release March 2024"], relatedOrgs:["AARO","Pentagon","DoD"], tags:["pentagon","declassified","2024","aaro"] },
  { id:"peru2023", name:"Peru Alleged Alien Encounter", date:"2023-07-12", location:"Ikitu, Loreto, Peru", lat:-3.74, lng:-73.25, classification:"REPORTED", evidenceLevel:"LOW", description:"Peruvian teenager reported attacks by 'alien beings' with metallic suits in the Amazon. Local police investigated. Viral internationally. Peru government acknowledged the reports.", witnesses:["Peruvian Teenagers","Local Police","Village Elders"], documents:["Peru Police Report 2023","BBC Investigation","Reuters Report July 2023"], relatedOrgs:["Peru National Police","Peruvian Government"], tags:["civilian","south-america","2023","controversial"] },
  { id:"uap2023hearings", name:"US Congress UAP Hearings", date:"2023-07-26", location:"US Capitol, Washington DC", lat:38.89, lng:-77.00, classification:"CONFIRMED", evidenceLevel:"HIGH", description:"Historic open Congressional hearing on UAP. Grusch, Fravor and Graves testified. Multiple witnesses cited under penalty of perjury. Led to UAP Disclosure Act 2023.", witnesses:["David Grusch","David Fravor","Ryan Graves","Representatives"], documents:["Full Congressional Testimony Transcript","UAP Disclosure Act 2023","NDAA 2024 UAP Provisions"], relatedOrgs:["House Oversight Committee","Congressional UAP Caucus","DoD"], tags:["congress","2023","historic","disclosure"] },
  { id:"mexico2023", name:"Mexico Congress Alleged Non-Human Bodies", date:"2023-09-13", location:"Mexico City, Mexico", lat:19.43, lng:-99.13, classification:"ALLEGED", evidenceLevel:"LOW", description:"Journalist Jaime Maussan presented alleged 'non-human' bodies to Mexican Congress. Scientists dispute the claims. NASA, UNAM and other institutions found no evidence of alien origin.", witnesses:["Jaime Maussan","Jose de Jesus Zalce Benitez","Mexican Congress Members"], documents:["Mexican Congress Session Recording","UNAM Scientific Analysis","DNA Test Results"], relatedOrgs:["Mexican Congress","UNAM","NASA"], tags:["mexico","controversial","2023","alleged"] },
  { id:"br_official_night", name:"Official UFO Night (Brazil)", date:"1986-05-19", location:"São Paulo / Rio airspace, Brazil", lat:-23.55, lng:-46.63, classification:"DECLASSIFIED", evidenceLevel:"HIGH", description:"21 UFOs tracked over four Brazilian states by FAB's CINDACTA radar. Five fighter jets scrambled to intercept. Confirmed by the Minister of Aeronautics in a press conference. Official report released 2009 as part of the National Archives UFO collection.", witnesses:["FAB Fighter Pilots","CINDACTA Radar Operators","Minister of Aeronautics Octávio Moreira Lima"], documents:["FAB Official Night Report (2009)","CINDACTA Radar Logs","Brazil National UFO Archives"], relatedOrgs:["Brazilian Air Force (FAB)","Arquivo Nacional","CINDACTA"], tags:["military","radar","government","south-america","declassified"] },
  { id:"br_operacao_prato", name:"Operação Prato / Colares", date:"1977-09-01", location:"Colares, Pará, Brazil", lat:-0.94, lng:-48.29, classification:"DECLASSIFIED", evidenceLevel:"MEDIUM", description:"Brazilian Air Force operation (1977–1978) investigating 'Chupa-Chupa' light beams that allegedly burned and wounded residents of Colares island. Produced official reports, photographs and film, later declassified into the National Archives.", witnesses:["Capt. Uyrangê Hollanda","Colares Residents","FAB Investigators"], documents:["Operação Prato Reports","FAB Photographs & Film","Brazil National UFO Archives"], relatedOrgs:["Brazilian Air Force (FAB)","Arquivo Nacional"], tags:["military","landing","injuries","south-america","declassified"] },
  { id:"br_varginha", name:"Varginha Incident", date:"1996-01-20", location:"Varginha, Minas Gerais, Brazil", lat:-21.55, lng:-45.43, classification:"REPORTED", evidenceLevel:"MEDIUM", description:"Brazil's 'Roswell': residents reported strange creatures and a UFO, with alleged military recovery operations. The Army said it was a misidentification; campaigners continue to demand the full files, part of the National Archives release.", witnesses:["Three Varginha Girls","Local Residents","Firefighters"], documents:["Varginha IPM Files","Brazil National UFO Archives"], relatedOrgs:["Brazilian Army","Arquivo Nacional"], tags:["civilian","creature","cover-up","south-america","1996"] },
] as const;

export const UAP_PEOPLE = [
  { id:"grusch", name:"David Grusch", role:"Intelligence Officer / Whistleblower", affiliation:"NRO / AARO", clearance:"TS/SCI", bio:"Former NRO representative to AARO. Testified under oath before Congress in July 2023 that the US government possesses non-human craft and biologics. Filed complaint with IC Inspector General who found his claims credible and urgent.", significance:"HIGH", linkedIncidents:["grusch","uap2023hearings"], linkedOrgs:["NRO","AARO","DIA"] },
  { id:"elizondo", name:"Luis Elizondo", role:"Former AATIP Director", affiliation:"US Army / TTSA", clearance:"TS/SCI (former)", bio:"Led Pentagon's AATIP from 2010-2017. Resigned in protest over secrecy. Co-founded To The Stars Academy. Instrumental in declassifying Nimitz and Roosevelt videos.", significance:"HIGH", linkedIncidents:["nimitz","roosevelt"], linkedOrgs:["AATIP","TTSA","DoD"] },
  { id:"fravor", name:"David Fravor", role:"US Navy Commander (Ret.)", affiliation:"US Navy", clearance:"Former Military", bio:"Primary witness to USS Nimitz Tic-Tac encounter 2004. Described 40-foot white object mirroring his aircraft. Testified before Congress 2023.", significance:"HIGH", linkedIncidents:["nimitz","uap2023hearings"], linkedOrgs:["USS Nimitz Strike Group","US Navy"] },
  { id:"graves", name:"Ryan Graves", role:"F/A-18 Pilot (Ret.)", affiliation:"Americans for Safe Aerospace", clearance:"Former Military", bio:"Former US Navy pilot who reported near-daily UAP encounters off East Coast 2014-2015. Founded Americans for Safe Aerospace. Testified before Congress 2023.", significance:"HIGH", linkedIncidents:["roosevelt","uap2023hearings"], linkedOrgs:["US Navy","Americans for Safe Aerospace"] },
  { id:"mellon", name:"Christopher Mellon", role:"Former Deputy Asst SecDef for Intelligence", affiliation:"DoD / TTSA", clearance:"Former TS/SCI", bio:"Served as Deputy Asst SecDef for Intelligence 1997-2002. Key role in getting Pentagon videos declassified. Advisor to TTSA.", significance:"HIGH", linkedIncidents:["nimitz","roosevelt"], linkedOrgs:["DoD","TTSA"] },
  { id:"kirkpatrick", name:"Sean Kirkpatrick", role:"Former AARO Director", affiliation:"DoD / AARO", clearance:"TS/SCI (former)", bio:"First director of AARO 2022-2023. Led the Pentagon's official UAP investigation. Released AARO Historical Record Report. Contradicted several whistleblower claims in public statements.", significance:"HIGH", linkedIncidents:["aaro2024"], linkedOrgs:["AARO","DoD","DIA"] },
  { id:"nolan", name:"Gary Nolan", role:"Stanford Professor / Immunologist", affiliation:"Stanford University", clearance:"None", bio:"Professor of Pathology at Stanford. Analyzed UAP-related biological effects on humans for CIA. Published peer-reviewed research on anomalous brain structures in UAP witnesses.", significance:"MEDIUM", linkedIncidents:[], linkedOrgs:["Stanford","CIA","TTSA"] },
  { id:"delonge", name:"Tom DeLonge", role:"Musician / TTSA Founder", affiliation:"To The Stars Academy", clearance:"None", bio:"Blink-182 musician who founded To The Stars Academy with former DoD officials. Established official channels with Pentagon insiders. Instrumental in public UAP disclosure movement.", significance:"MEDIUM", linkedIncidents:[], linkedOrgs:["TTSA"] },
] as const;

export const UAP_ORGANIZATIONS = [
  { id:"aaro", name:"AARO", fullName:"All-domain Anomaly Resolution Office", type:"Government", founded:"2022", status:"ACTIVE", description:"The Pentagon's official office for detecting, identifying and attributing UAP. Established by NDAA 2022. Reports to Deputy SecDef and DNI.", transparency:"LOW", url:"https://www.aaro.mil" },
  { id:"aatip", name:"AATIP", fullName:"Advanced Aerospace Threat Identification Program", type:"Government", founded:"2007", status:"DISSOLVED", description:"Secret Pentagon program funded by $22M through Senator Harry Reid. Ran 2007-2012 officially. Produced reports on UAP propulsion and biological effects.", transparency:"VERY LOW", url:"https://en.wikipedia.org/wiki/Advanced_Aerospace_Threat_Identification_Program" },
  { id:"ttsa", name:"TTSA", fullName:"To The Stars Academy of Arts & Science", type:"Private", founded:"2017", status:"ACTIVE", description:"Founded by Tom DeLonge with former DoD officials. Instrumental in releasing Nimitz/Roosevelt videos. Allegedly acquired UAP metamaterial samples.", transparency:"MEDIUM", url:"https://www.tothestarsacademy.com" },
  { id:"dia", name:"DIA", fullName:"Defense Intelligence Agency", type:"Government", founded:"1961", status:"ACTIVE", description:"Primary US military intelligence agency. Funded AATIP. Produced classified reports on UAP propulsion. David Grusch's testimony implicates DIA in crash retrieval programs.", transparency:"VERY LOW", url:"https://www.dia.mil" },
  { id:"bigelow", name:"BAASS", fullName:"Bigelow Aerospace Advanced Space Studies", type:"Private", founded:"1999", status:"DORMANT", description:"Founded by Robert Bigelow. Received $22M AATIP contract. Investigated Skinwalker Ranch. Bigelow publicly stated ETs are here on 60 Minutes.", transparency:"LOW", url:"https://bigelowaerospace.com" },
  { id:"nro", name:"NRO", fullName:"National Reconnaissance Office", type:"Government", founded:"1961", status:"ACTIVE", description:"US spy satellite agency. David Grusch served as NRO representative to AARO. Grusch testified NRO has significant classified UAP programs.", transparency:"VERY LOW", url:"https://www.nro.gov" },
  { id:"asa", name:"ASA", fullName:"Americans for Safe Aerospace", type:"NGO", founded:"2022", status:"ACTIVE", description:"Founded by Ryan Graves to advocate for UAP transparency and pilot safety reporting. Works with Congress and media to normalize UAP reporting by military pilots.", transparency:"HIGH", url:"https://www.americansforsafeaerospace.org" },
  { id:"blackvault", name:"The Black Vault", fullName:"The Black Vault FOIA Database", type:"NGO", founded:"1996", status:"ACTIVE", description:"World's largest online repository of government FOIA documents. Run by John Greenewald Jr. Contains millions of pages of declassified UAP/UFO records from CIA, FBI, NSA, DIA.", transparency:"HIGH", url:"https://www.theblackvault.com" },
  { id:"arquivo_nacional", name:"Arquivo Nacional (Brazil)", fullName:"Arquivo Nacional do Brasil / FAB UFO Collection", type:"Government", founded:"1838", status:"ACTIVE", description:"Brazil's National Archives. Holds the official UFO/UAP collection — 893 declassified cases (1952–2023) transferred by the Brazilian Air Force under Ordinance 551/GC3. Publicly searchable via the SIAN platform, making Brazil one of the most transparent states on UAP records.", transparency:"HIGH", url:"https://sian.an.gov.br/sianex/consulta/login.asp" },
] as const;

export const UAP_DOCUMENTS = [
  { id:"flir1", name:"FLIR1 Video (Tic-Tac)", year:2020, type:"Video", classification:"DECLASSIFIED", url:"https://www.defense.gov/Newsroom/Releases/Release/Article/2165713/statement-by-the-department-of-defense-on-the-release-of-historical-navy-videos/", description:"Pentagon-released infrared video of USS Nimitz Tic-Tac encounter 2004. Shows object performing impossible maneuvers." },
  { id:"gimbal", name:"Gimbal Video", year:2020, type:"Video", classification:"DECLASSIFIED", url:"https://www.defense.gov/Newsroom/Releases/Release/Article/2165713/", description:"Shows rotating object off US East Coast with no known propulsion. Pilots audible on recording." },
  { id:"gofast", name:"GoFast Video", year:2020, type:"Video", classification:"DECLASSIFIED", url:"https://www.defense.gov/Newsroom/Releases/Release/Article/2165713/", description:"US Navy video showing UAP moving at extraordinary speed near ocean surface." },
  { id:"uaptf2021", name:"ODNI UAP Preliminary Assessment", year:2021, type:"Report", classification:"PARTIALLY DECLASSIFIED", url:"https://www.dni.gov/files/ODNI/documents/assessments/Prelimary-Assessment-UAP-20210625.pdf", description:"Examined 144 UAP reports. Could not explain 143. Raised national security and flight safety concerns." },
  { id:"aaro2024v1", name:"AARO Historical Record Report Vol.1", year:2024, type:"Report", classification:"PARTIALLY DECLASSIFIED", url:"https://www.aaro.mil/Portals/136/PDFs/FY2024/Historical_Record_Report_Volume_1_2024.pdf", description:"AARO's official historical review of 70+ years of US government UAP programs. Reviews all known programs." },
  { id:"aaro2024v2", name:"AARO Historical Record Report Vol.2", year:2024, type:"Report", classification:"PARTIALLY DECLASSIFIED", url:"https://www.aaro.mil/Portals/136/PDFs/FY2024/Historical_Record_Report_Volume_2_2024.pdf", description:"Volume 2 of AARO's comprehensive historical review. Includes additional cases and program analysis." },
  { id:"pbb", name:"Project Blue Book Files", year:1969, type:"Archive", classification:"DECLASSIFIED", url:"https://www.fold3.com/title/471/project-blue-book-ufo-investigations", description:"12,618 UAP sightings investigated 1952-1969. 701 remain unidentified. Full archive available." },
  { id:"ciaufo", name:"CIA UFO Collection", year:2021, type:"Archive", classification:"DECLASSIFIED", url:"https://www.cia.gov/readingroom/collection/ufo-general-collection", description:"CIA FOIA Reading Room UFO/UAP document collection. Thousands of pages released under FOIA requests." },
  { id:"fbivault", name:"FBI Vault UFO Files", year:2011, type:"Archive", classification:"DECLASSIFIED", url:"https://vault.fbi.gov/UFO", description:"FBI's official FOIA release of UFO-related documents. Includes the famous 1950 Hottel Memo about recovered saucers." },
  { id:"hottel", name:"Guy Hottel Memo", year:1950, type:"Document", classification:"DECLASSIFIED", url:"https://vault.fbi.gov/UFO/UFO%20Part%201%20of%2016/view", description:"1950 FBI memo describing recovered flying saucers and 'human-like' bodies from New Mexico. Most requested document in FBI history." },
  { id:"dia_reports", name:"DIA AATIP Technical Reports", year:2018, type:"Report", classification:"PARTIALLY DECLASSIFIED", url:"https://www.theblackvault.com/documentarchive/the-advanced-aerospace-threat-identification-program-aatip-documents/", description:"38 technical reports produced under AATIP contract covering UAP propulsion, materials, and biological effects on humans." },
  { id:"grusch_testimony", name:"Grusch Congressional Testimony", year:2023, type:"Testimony", classification:"PUBLIC", url:"https://oversight.house.gov/hearing/unidentified-anomalous-phenomena-implications-on-national-security-public-safety-and-government-transparency/", description:"Historic UAP hearing. Grusch, Fravor, Graves testify under oath. Most-watched Congressional hearing in years." },
  { id:"ndaa2024_uap", name:"NDAA 2024 UAP Provisions", year:2023, type:"Legislation", classification:"PUBLIC", url:"https://www.congress.gov/bill/118th-congress/senate-bill/2226", description:"National Defense Authorization Act 2024 includes UAP Disclosure Act provisions requiring declassification of UAP records within 25 years." },
  { id:"uap_disclosure_act", name:"UAP Disclosure Act 2023", year:2023, type:"Legislation", classification:"PUBLIC", url:"https://www.congress.gov/bill/118th-congress/senate-bill/2503/text", description:"Bipartisan bill modeled on JFK Assassination Records Act. Would force declassification of all UAP records and create independent review board." },
  { id:"grusch_ig", name:"Grusch Inspector General Complaint", year:2023, type:"Document", classification:"PARTIALLY DECLASSIFIED", url:"https://www.politico.com/news/2023/06/05/intelligence-officials-say-ufo-crash-retrieval-00100077", description:"David Grusch's formal complaint to Intelligence Community Inspector General about crash retrieval programs. IG found complaint credible and urgent." },
  { id:"french_cometa", name:"COMETA Report (France)", year:1999, type:"Report", classification:"PUBLIC", url:"https://www.ufoevidence.org/documents/doc1877.htm", description:"French military and government study of UFO phenomenon. Concluded UAP are real, physical objects of possible extraterrestrial origin. Signed by retired generals and scientists." },
  { id:"uk_mod", name:"UK MoD UFO Files", year:2013, type:"Archive", classification:"DECLASSIFIED", url:"https://www.nationalarchives.gov.uk/ufos/", description:"UK National Archives UFO files released 2008-2013. 209 files covering 1950-2009. Thousands of reported sightings and government investigations." },
  { id:"br_national_archives", name:"Brazil National UFO Archives (893 cases)", year:2023, type:"Archive", classification:"DECLASSIFIED", url:"https://sian.an.gov.br/sianex/consulta/login.asp", description:"Brazil's Arquivo Nacional has published 893 declassified UFO/UAP case files spanning 1952–2023 — photos, audio, drawings and military reports transferred by the Brazilian Air Force (FAB) under Ordinance 551/GC3 (2009). Browse the full collection chronologically via the SIAN (National Archive Information System) platform." },
  { id:"br_official_night_1986", name:"Official UFO Night (Noite Oficial dos OVNIs)", year:1986, type:"Report", classification:"DECLASSIFIED", url:"https://www.gov.br/en/government-of-brazil/latest-news/2022/official-ufo-night-in-brazil", description:"On 19 May 1986, 21 UFOs (some up to 100m wide) were tracked over four states by FAB's CINDACTA radar; five fighter jets were scrambled to intercept. The Minister of Aeronautics confirmed it in a 23 May 1986 press conference. The official report was released in 2009." },
  { id:"br_operacao_prato", name:"Operação Prato / Colares (FAB)", year:1977, type:"Report", classification:"DECLASSIFIED", url:"https://en.wikipedia.org/wiki/Opera%C3%A7%C3%A3o_Prato", description:"Brazilian Air Force investigation (1977–1978) into the 'Chupa-Chupa' light-beam events on Colares island, Pará, where residents reported burns and puncture wounds. Produced hundreds of pages of official reports, photographs and film, later declassified." },
  { id:"br_varginha", name:"Varginha Incident — IPM Files", year:1996, type:"Document", classification:"DECLASSIFIED", url:"https://en.wikipedia.org/wiki/Varginha_UFO_incident", description:"Brazil's 'Roswell': January 1996 reports of strange creatures and a UFO in Varginha, Minas Gerais, with alleged military recovery. The military police inquiry (IPM) files are part of the National Archives release." },
  { id:"br_trindade_1958", name:"Caso Ilha da Trindade (Brazilian Navy)", year:1958, type:"Document", classification:"DECLASSIFIED", url:"https://en.wikipedia.org/wiki/UFO_sightings_in_Brazil", description:"16 January 1958: a Saturn-shaped object was photographed by Almiro Baraúna from the Navy ship Almirante Saldanha near Trindade Island. The Brazilian Navy authenticated the negatives — one of the most documented official UFO photo cases." },
] as const;

export type UapIncident = (typeof UAP_INCIDENTS)[number];
export type UapPerson = (typeof UAP_PEOPLE)[number];
export type UapOrganization = (typeof UAP_ORGANIZATIONS)[number];
export type UapDocument = {
  id: string;
  name: string;
  year: number;
  type: string;
  classification: string;
  url: string;
  description: string;
};
